apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications
  template:
    metadata:
      labels:
        app: applications
    spec:
      containers:
        - name: applications
          image: phromin/applications
          env:
            - name: NATS_CLUSTER_ID
              value: 'recruitment'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: applications-srv 
spec:
  selector:
    app: applications
  ports:
    - name: applications
      protocol: TCP
      port: 3000
      targetPort: 3000