apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/jobs
            backend:
              serviceName: jobs-srv
              servicePort: 3000
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-srv-with-auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/auth-url: http://auth-srv.default.svc.cluster.local:3000/api/users/authenticate
    nginx.ingress.kubernetes.io/auth-response-headers: user-id, user-role
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/jobs/create
            backend:
              serviceName: jobs-srv
              servicePort: 3000
          - path: /api/applications
            backend:
              serviceName: applications-srv
              servicePort: 3000
