apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
        - name: jobs
          image: phromin/jobs
          env:
            - name: NATS_CLUSTER_ID
              value: 'recruitment'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-svc:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-srv 
spec:
  selector:
    app: jobs
  ports:
    - name: jobs
      protocol: TCP
      port: 3000
      targetPort: 3000